version: '3.8'

services:
  fraud-detection-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fraud-detection-api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=../mlflow/mlflow.db
    volumes:
      - ../mlruns:/app/mlruns
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3